---
version: '3.8'
services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
    networks:
      - frontend_net
    command:
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=black.ghost75020@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    deploy:
      placement:
        constraints: ["node.role == manager"]
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.4
    networks:
      - backend_net
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    healthcheck:
      test: >-
        ["CMD-SHELL", "wget --no-check-certificate -qO- https://localhost:9200/_cluster/health?wait_for_status=yellow
        -u admin:$$OPENSEARCH_PASSWORD_SECRET || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 120s
    secrets:
      - source: wazuh_admin_password
        target: OPENSEARCH_PASSWORD_SECRET
    deploy:
      replicas: 1
  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.4
    networks:
      - backend_net
    volumes:
      - wazuh-manager-data:/var/ossec/data
    deploy:
      replicas: 1
  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.4
    environment:
      - WAZUH_API_URL=http://wazuh-manager:55000
    configs:
      - source: wazuh_dashboard_config
        target: /usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
    networks:
      - frontend_net
      - backend_net
    secrets:
      - source: wazuh_admin_user
        target: OPENSEARCH_USERNAME
      - source: wazuh_admin_password
        target: OPENSEARCH_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wazuh.rule=Host(`ghost-wazuh-soc.duckdns.org`)"
        - "traefik.http.routers.wazuh.entrypoints=websecure"
        - "traefik.http.routers.wazuh.tls.certresolver=letsencrypt"
        - "traefik.http.services.wazuh.loadbalancer.server.port=5601"
        - "traefik.docker.network=frontend_net"
volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
  traefik-certs:
networks:
  frontend_net:
    external: true
  backend_net:
    external: true
secrets:
  wazuh_admin_user:
    external: true
  wazuh_admin_password:
    external: true
configs:
  wazuh_dashboard_config:
    external: true
