version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
    networks:
      - frontend_net
    command:
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=black.ghost75020@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    deploy:
      placement:
        constraints: [node.role == manager]

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.4
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    networks:
      - backend_net
    deploy:
      replicas: 1

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.4
    volumes:
      - wazuh-manager-data:/var/ossec/data
    networks:
      - backend_net
    depends_on:
      - wazuh-indexer
    deploy:
      replicas: 1

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.4
    networks:
      - frontend_net
      - backend_net
    secrets:
      - source: wazuh_admin_user
        target: OPENSEARCH_USERNAME
      - source: wazuh_admin_password
        target: OPENSEARCH_PASSWORD
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wazuh.rule=Host(`ghost-wazuh-soc.duckdns.org`)"
        - "traefik.http.routers.wazuh.entrypoints=websecure"
        - "traefik.http.routers.wazuh.tls.certresolver=letsencrypt"
        - "traefik.http.services.wazuh.loadbalancer.server.port=5601"
        - "traefik.docker.network=frontend_net"

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
  traefik-certs:

networks:
  frontend_net:
    external: true
  backend_net:
    external: true

secrets:
  wazuh_admin_user:
    external: true
  wazuh_admin_password:
    external: true
