---
- name: Deploy Wazuh SOC Stack to Docker Swarm
  hosts: swarm_managers
  gather_facts: no
  vars:
    ansible_user: runnerv2
  vars_files:
    - ../vault.yml

  tasks:
    - name: Ensure configuration directory exists on manager
      ansible.builtin.file:
        path: /home/runnerv2/configs
        state: directory
        mode: '0755'

    - name: Copy Wazuh stack file to the manager node
      ansible.builtin.copy:
        src: ../stack/wazuh-stack.yml # Chemin corrigé
        dest: /home/runnerv2/configs/wazuh-stack.yml

    - name: Copy Wazuh dashboard config file to the manager node
      ansible.builtin.copy:
        src: ../stack/configs/wazuh-dashboard.yml # Chemin corrigé
        dest: /home/runnerv2/configs/wazuh-dashboard.yml

    - name: Create Wazuh dashboard config object in Docker Swarm
      community.docker.docker_config:
        name: "wazuh_dashboard_config"
        data: "{{ lookup('file', '../../ansible/stack/configs/wazuh-dashboard.yml') }}" # Chemin corrigé
        state: present

    - name: Deploy/Update Wazuh Stack
      community.docker.docker_stack:
        state: present
        name: "wazuh_soc"
        compose:
          - /home/runnerv2/configs/wazuh-stack.yml
      register: stack_deployment_result

    - name: Initialize/Update Wazuh Indexer Security Configuration
      ansible.builtin.shell: >
        docker exec
        $(docker ps --filter "name=wazuh_soc_wazuh-indexer" -q)
        bash -c "JAVA_HOME=/usr/share/wazuh-indexer/jdk bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh
        -cd /usr/share/wazuh-indexer/opensearch-security/
        -nhnv
        -cacert /usr/share/wazuh-indexer/certs/root-ca.pem
        -cert /usr/share/wazuh-indexer/certs/admin.pem
        -key /usr/share/wazuh-indexer/certs/admin-key.pem"
      register: security_admin_result
      until: security_admin_result.rc == 0
      retries: 5
      delay: 10
      changed_when: "'DONE' in security_admin_result.stdout"
      when: stack_deployment_result.changed
