---
name: CI/CD Wazuh SOC Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint Code
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linters
        run: pip3 install yamllint ansible-lint

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        env:
          # On donne un faux mot de passe juste pour que le linter puisse passer
          ANSIBLE_VAULT_PASSWORD: "lint-password"
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass_lint.txt
          ansible-lint ansible/playbooks/ --vault-password-file .vault_pass_lint.txt
          rm .vault_pass_lint.txt

  # ... (Le reste des jobs scan, test, deploy ne change pas) ...
  scan:
    name: Scan for Vulnerabilities
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Scan wazuh/wazuh-dashboard image with Trivy
        run: |
          echo "Étape de scan Trivy à implémenter ici."
          echo "Scan réussi (placeholder)"
  test:
    name: Run Selenium UI Tests
    needs: scan
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Selenium tests
        run: |
          echo "Étape de test Selenium à implémenter ici."
          echo "Tests réussis (placeholder)"
  deploy:
    name: Deploy to Production
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Activate Python venv and Deploy
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
        run: |
          source $GITHUB_WORKSPACE/ansible_env/bin/activate
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt
          ansible-playbook -i ansible/inventories/production.ini ansible/playbooks/deploy.yml --vault-password-file vault_pass.txt
          rm vault_pass.txt
